Hindi demonstration video
sudiptob2/cf-stats pull request #51
Opened 2022-10-28 22:46 UTC by shubhankarsharma876

Added the tutorial video link in the readme file.

2022-10-29 17:51 UTC, sudiptob2 commented
Hey great effort! I saw the video.  There is a mistake though. You said it generates the stat in every 15 min, but by default it generates in every 24 hours. I will accept this PR not to block your contribution but, can you please update that ( like putting a text quote on the video regarding the mistakes) in the mean time ? 🙏

2022-10-30 04:43 UTC, sudiptob2 requested changes

2022-10-30 04:43 UTC, sudiptob2 commented on README.md
> +## For video tutorial demonstration (in Hindi) do [visit](https://www.youtube.com/watch?v=SMHzbmtHLMo)
```suggestion
## Video Demonstration 
- [Hindi](https://www.youtube.com/watch?v=SMHzbmtHLMo)
```

2022-10-30 04:46 UTC, sudiptob2 requested changes

2022-10-30 04:46 UTC, sudiptob2 commented on README.md
> +## Video Demonstration
```suggestion
```

2022-10-30 04:46 UTC, sudiptob2 commented on README.md
> +- [Hindi](https://www.youtube.com/watch?v=SMHzbmtHLMo)
```suggestion
```

2022-10-30 04:51 UTC, sudiptob2 requested changes

2022-10-30 04:51 UTC, sudiptob2 commented on README.md
> +## For step by step screenshot go [here](docs/INSTALLATIONSTEPS.md)
```suggestion
### For step-by-step screenshots go [here](docs/INSTALLATIONSTEPS.md) 
### Video Demonstration
  - [Hindi](https://www.youtube.com/watch?v=SMHzbmtHLMo)
```

2022-10-30 04:54 UTC, merged

2022-10-30 14:59 UTC, shubhankarsharma876 commented
Yes for sure no problem...